const cpuI = Math.floor(Math.random() * 100);
const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "How does a penguin build its house? Igloos it together!",
    "I used to play piano by ear, but now I use my hands.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the mathematician who’s afraid of negative numbers? He will stop at nothing to avoid them.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm on a whiskey diet. I've lost three days already.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a banker, but I lost interest.",
    "How do you organize a space party? You planet!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm on a whiskey diet. I've lost three days already.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the mathematician who’s afraid of negative numbers? He will stop at nothing to avoid them.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to be a banker, but I lost interest.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm on a whiskey diet. I've lost three days already.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the mathematician who’s afraid of negative numbers? He will stop at nothing to avoid them.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to be a banker, but I lost interest.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I'm on a whiskey diet. I've lost three days already.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Did you hear about the mathematician who’s afraid of negative numbers? He will stop at nothing to avoid them.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to be a banker, but I lost interest.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
    "I used to be a gardener, but I couldn't find my roots.",
    "Why are ghosts bad at lying? Because you can see right through them!",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's a vampire's favorite fruit? A blood orange.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "I used to be a baker, but I couldn't make enough dough.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet."
  ];
const selectedJoke = jokes[cpuI];
document.getElementById("joke").innerHTML=(selectedJoke);
let relaod = document.getElementById("reload");
relaod.addEventListener("click", function(){
  window.location.href = "./english.html";
})

let hindi = document.getElementById("hindi");
hindi.addEventListener("click", function(){
    window.location.href = "./index.html"
})